##############
# WORLD INFO #
##############
random_world: false

valid_worlds:
  - world

radius:
  max_X: 1000
  max_Z: 1000
  min_X: 0
  min_Z: 0
  
######################
# PRICE AND COOLDOWN #
######################
price: 0.0

cooldown: 0
 
portal:
  price: false
  cooldown: false
sign:
  price: false
  cooldown: false
self:
  price: false
  cooldown: false
cmd:
  price: false
  cooldown: false
  
##############
# BLACK LIST #
##############
biomes:
  - COLD_OCEAN
  - DEEP_COLD_OCEAN
  - DEEP_FROZEN_OCEAN
  - DEEP_LUKEWARM_OCEAN
  - DEEP_OCEAN
  - DEEP_WARM_OCEAN
  - FROZEN_OCEAN
  - FROZEN_RIVER
  - LUKEWARM_OCEAN
  - OCEAN
  - WARM_OCEAN
blocks:
  - CACTUS

######################
# PLUGIN INTEGRATION #
######################
towny: false
factions: false
worldguard: false
worldborder: false

########
# MISC #
########
debug: false
send_message_on_tp: false
anticheat: false
preventPortalUpdate: true
oneTimeUse: false