name: ${project.artifactId}
version: ${project.version}
description: ${project.artifactId}
main: backcab.RandomTP.RandomTP
softdepend: [GriefPrevention, WorldGuard, WorldBorder]
api-version: 1.15
commands:
  randomtp:
    usage: /randomtp [player|reload]
    description: randomly teleports you or another player
    aliases: [rtp]
permissions:
  randomtp.tp:
    description: Teleports the executing user to a random location on the map.
    default: false
  randomtp.other:
    description: Teleports another user then the executing user to a random location on the map.
    default: false
  randomtp.reload:
    description: Reloads the plugin configuration.
    default: false
