name: ${project.artifactId}
version: ${project.version}
description: ${project.artifactId}
main: backcab.RandomTP.RandomTP
softdepend: [Towny,WorldGuard,Factions,WorldBorder,Vault]
api-version: 1.14
commands:
  randomtp:
    usage: /randomtp [player|portal|reload]
    description: randomly teleports you or another player
    aliases: [rtp]